#!/bin/bash
./scripts/build-model.sh 
ask deploy --force                                                                                                                                                                                              